[16:47]  [ERROR] Exception in ./scan.py
[16:47]  [SUMMARY] 192.168.174.1 - Ports: []
[16:47]  [SUMMARY] 192.168.174.1 - Services: []
[16:50]  [ERROR] Exception in ./scan.py
[16:50]  [SUMMARY] 192.168.174.1 - Ports: []
[16:50]  [SUMMARY] 192.168.174.1 - Services: []
[17:16]  [ERROR] Exception in ./scan.py
[17:16]  [SUMMARY] 192.168.174.1 - Ports: []
[17:16]  [SUMMARY] 192.168.174.1 - Services: []
